print("Twinkle, twinkle, little star,")
print("\n\tHow I wonder what you are!")
print("\n\t\tUp above the world so high,")
print("\n\t\tLike a diamond in the sky.")
print("\nTwinkle, twinkle, little star,")
print("\n\tHow I wonder what you are")